// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dgbywhahjoybixqnrovy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRnYnl3aGFoam95Yml4cW5yb3Z5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzMzY0NTEsImV4cCI6MjA2NTkxMjQ1MX0.IDzsm_IcL40GLxMOvTV1IfmDaLcSs6qeWT9I4XJ0DmE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);